### ISSUE TITLE
Plan: Python 3.8 support for Ubuntu 20.04

### ISSUE THREAD

**Issue by nzlosh** [StackStorm/discussions#68]
As per the TSC discussion on 2nd March 2021 it was decided to add support for Python3.8 on Ubuntu 20.04 (focal).

To achieve this goal, the following actions must be carried out:

- [ ] st2
  - [x] add support for mongodb 4.4 (Only mongodb-server v4.4 packages for Focal)
    Bump pymongo to >=3.11 (https://docs.mongodb.com/drivers/pymongo/#mongodb-compatibility)
  - [x] Mongo 4.4 compatibility tracked in issue https://github.com/StackStorm/st2/issues/5249
  - [x] add support for python3.8 to unit tests (github actions)
  - [ ] add support for unit tests to run against mongo 4.0 and 4.4 (github actions)
  - [x] update version of eventlet to >=27.0 to benefit from monkey patch supporting python3.7+ threading.
  - [x] Add focal to .circleci packages - https://github.com/StackStorm/st2/pull/5283
- [x] st2-packages
  - [x] Integrate focal package building.
  - [x] Add focal to CircleCI package build.
  - [x] Add python3.8 to cli test post package build.
- [x] st2packaging-dockerfiles
  - [x] Add `focal` to **packagingbuild**.
  - [x] Add `focal` to **packagingtest**.
  - [x] Publish docker images.
- [x] st2ci
  - [x] changes for unstable runs and PR runs - @amanda11 
  - [x] changes for stable runs - @amanda11 
- [x] stcd
  - [x] changes for unstable runs - @amanda11 
  - [x] changes for release - @amanda11 
- [x] ansible-st2 - @winem 
  - [x] pre-release changes for U20
  - [x] post-release travis runs for stable U20 
- [x] puppet-st2 @rush-skills
- [x] st2docs
  - [x] https://github.com/StackStorm/st2docs/pull/1072
- [x] orquesta
  - [x] unit-tests updated with python3.8 support. https://github.com/StackStorm/orquesta/pull/236
 - [X] st2chatops - update O/S built on - @amanda11 
 - [x] st2web - add focal to builds @amanda11 
 - [x] st2-aut-ldap https://github.com/StackStorm/st2-auth-ldap/pull/95 thanks @amanda11 
 - [x] st2-rbac-backend https://github.com/StackStorm/st2-rbac-backend/pull/52 thanks @amanda11

**Comment by arm4b** [comment]
That's very helpful, thanks a lot @nzlosh :+1: 
cc @winem

**Comment by Kami** [comment]
Just FYI - https://github.com/StackStorm/st2vagrantdev/pull/12.

**Comment by Kami** [comment]
>  add support for unit tests to run against mongo 4.0, 4.2 and 4.4 (github actions)

As discussed on Slack, that's probably not easily achievable at this point since it would inflate our build matrix and slow things down too much.

In the past, we did run tests against multiple MongoDB versions on Travis CI, but it got removed since it was slow.

So our option is to run unit + integration tests only against Mongo 4.0 or Mongo 4.4.

Right now we use 4.4, which I think is fine and probably better since there are some small changes with projection queries which used to work in MongoDB 4.0, but not in 4.4 - so in theory, as long as those tests pass on 4.4, they should also pass on 4.0.

And we will have some version specific coverage with end to end tests anyway (Bionic will exercise 4.0 and Focal will exercise 4.4).

**Comment by nzlosh** [comment]
The focal packages are now available on packagecloud.
@nmaludy do you have the bandwidth to integrate focal with puppet?
@amanda11 / @winem do either of you have bandwidth to integrate focal with ansible?

**Comment by arm4b** [comment]
+@cognifloyd, hopefully, he could also help with adding U20 for Ansible.

**Comment by rush-skills** [comment]
Currently, we don't run integration tests against python3.8 in puppet modules. Is this required? @amanda11 @nmaludy

**Comment by arm4b** [comment]
It looks we're all set here with adding py3.8 for Ubuntu20.
